runtime:
  run_mode: "local"
  device: "cpu"    # "cpu" untuk dev lokal, nanti bisa "cuda" di Kaggle
  seed: 42

data:
  dataset_name: "ag_news"
  text_column: "text"
  label_column: "label"
  max_train_samples: 2000    # subset untuk dev lokal (optional)
  max_eval_samples: 500      # subset untuk eval lokal (optional)

model:
  model_name: "distilbert-base-uncased"
  max_length: 256
  num_labels: 4
  # id2label dan label2id bisa ditambahkan nanti kalau sudah siap

training:
  output_dir_name: "model_1_classifier"
  num_train_epochs: 1
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 32
  learning_rate: 5e-5
  weight_decay: 0.0
  warmup_ratio: 0.0
  logging_steps: 50
  evaluation_strategy: "epoch"
  save_strategy: "epoch"
  metric_for_best_model: "f1"
  greater_is_better: true